### ISSUE TITLE
hay un codigo compilado basura debe sacarlo del repo

### ISSUE THREAD

**Issue by IoTeacher** [Aignister/50-Programas#2]
https://github.com/Aignister/50-Programas/blob/main/programa1

borrarlo es ejecutable en los repos no se presentan

**Comment by Aignister** [comment]
Ese repo, en el IDOCEO le habia puesto que ya no se iba a usar en los avances por lo del codigo basura, https://github.com/Aignister/50-Programas-Ensamblador.git
Ese es el que le habia puesto que era el actual

**Comment by IoTeacher** [comment]
[24bb_Interfaz_-_202412071036.pdf](https://github.com/user-attachments/files/18050986/24bb_Interfaz_-_202412071036.pdf)
